/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1a1c1c",
        "surface-dim": "#dadada",
        "surface-container-low": "#f3f3f3",
        "inverse-on-surface": "#f1f1f1",
        "on-secondary-fixed": "#001c3a",
        "surface-bright": "#f9f9f9",
        "on-primary-fixed": "#410003",
        "secondary-fixed-dim": "#a5c8ff",
        "on-surface-variant": "#5b403d",
        "primary-fixed": "#ffdad6",
        "on-primary-fixed-variant": "#930010",
        "surface-container-highest": "#e2e2e2",
        "surface-variant": "#e2e2e2",
        "on-surface": "#1a1c1c",
        "secondary-fixed": "#d4e3ff",
        "on-secondary-fixed-variant": "#004786",
        "inverse-surface": "#2f3131",
        "tertiary": "#715300",
        "secondary-container": "#54a0fe",
        "error-container": "#ffdad6",
        "primary-container": "#d32f2f",
        "surface-container": "#eeeeee",
        "tertiary-fixed": "#ffdfa0",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#f8bd2a",
        "surface-container-high": "#e8e8e8",
        "surface-tint": "#ba1a20",
        "secondary": "#005faf",
        "primary": "#af101a",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#261a00",
        "outline-variant": "#e4beba",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#5c4300",
        "primary-fixed-dim": "#ffb3ac",
        "on-tertiary-container": "#fff3e3",
        "error": "#ba1a1a",
        "on-secondary-container": "#003567",
        "on-error": "#ffffff",
        "inverse-primary": "#ffb3ac",
        "outline": "#8f6f6c",
        "tertiary-container": "#8f6a00",
        "on-primary": "#ffffff",
        "on-secondary": "#ffffff",
        "background": "#f9f9f9",
        "surface": "#f9f9f9",
        "on-primary-container": "#fff2f0",
        "brick-yellow": "#FFD700",
        "brick-blue": "#0055A4",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        gutter: "16px",
        "stack-overlap": "-4px",
        unit: "8px",
        "margin-mobile": "16px",
        "margin-desktop": "32px",
      },
      fontFamily: {
        "body-md": ["Work Sans", "sans-serif"],
        "body-lg": ["Work Sans", "sans-serif"],
        "label-caps": ["'LEGO BRIX'", "Space Mono", "monospace"],
        "display-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "button-text": ["'LEGO BRIX'", "Plus Jakarta Sans", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["'LEGO BRIX'", "Plus Jakarta Sans", "sans-serif"],
        "lego": ["'LEGO BRIX'", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.35", fontWeight: "700" }],
        "display-lg-mobile": ["32px", { lineHeight: "1.25", fontWeight: "800" }],
        "button-text": ["16px", { lineHeight: "1.35", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.35", fontWeight: "700" }],
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
      },
      animation: {
        marquee: "marquee 20s linear infinite",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
